on: [push, pull_request]
name: Selenium
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: set environment variables
      uses: allenevans/set-env@v2.0.0
      with:
        GO111MODULE: 'on' 

    - name: Install dependencies
      run: cd vendor && go run init.go --alsologtostderr --download_browsers --download_latest && cd ..
      
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Test
      run: go test ./...
