on: [push, pull_request]
name: Selenium
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: set environment variables
      uses: allenevans/set-env@v2.0.0
      with:
        'GO111MODULE': 'on'
        
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run headless test
      uses: GabrielBB/xvfb-action@v1
      with:
        working-directory: ./ #optional
        run: npm test

    - name: Install dependencies
      run: cd vendor && go run init.go --alsologtostderr --download_browsers --download_latest && cd ..
      
    - name: GO FMT
      run: ./testing/travis-ci-gofmt.sh

    - name: Test
      run: ./testing/travis-ci-test.sh
      
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash) -- -v
